spring:
  application:
    name: notification_service
  data:
    mongodb:
      uri: ${MONGODB_URI}
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

aws:
  region: us-east-2
  sqs:
    livro-alugado-queue-notification: livro-alugado-queue-notification
    livro-atualizado-queue-notification: livro-atualizado-queue-notification
    livro-lembrete-queue-notification: livro-lembrete-queue-notification
    livro-retornado-queue-notification: livro-retornado-queue-notification

server:
  port: 8082
